name: flutter_highlight_gallery
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter: { sdk: flutter }
  flutter_highlight: { path: ../ }
  url_launcher: ^6.0.2

flutter:
  uses-material-design: true

dependency_overrides:
  highlight: { path: ../../highlight }
