name: highlighting
description: Syntax highlighting for Dart with lots of languages and themes support.
version: 0.8.0
homepage: https://github.com/akvelon/dart-highlighting

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  equatable: ^2.0.5
  tuple: ^2.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  path: ^1.8.0
